<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-496DOAJ" failures="5" tests="7" name="Runner_Files.Help_positive_scenarios_runner" time="41.202" errors="0" timestamp="2021-07-12T21:57:21 IST" skipped="0">
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.185"/>
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.134">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.profile_displayed(Help_positive_scenarios.java:164)
at ✽.verify the Profile description is displayed(file:///C:/Users/Admin/Downloads/mph-web-qa-automation/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.141">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.awardspoints_displayed(Help_positive_scenarios.java:108)
at ✽.verify the Award Points description is displayed(file:///C:/Users/Admin/Downloads/mph-web-qa-automation/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.152">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.payments_displayed(Help_positive_scenarios.java:191)
at ✽.verify the Payments description is displayed(file:///C:/Users/Admin/Downloads/mph-web-qa-automation/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="40.331"/>
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.128">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.addcoverage_displayed(Help_positive_scenarios.java:217)
at ✽.verify the Add coverage description is displayed(file:///C:/Users/Admin/Downloads/mph-web-qa-automation/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:31)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner_Files.Help_positive_scenarios_runner" name="runScenario" time="0.131">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at Help_positive_scenarios.Help_positive_scenarios.secondopinions_displayed(Help_positive_scenarios.java:82)
at ✽.verify the Second Opinions description is displayed(file:///C:/Users/Admin/Downloads/mph-web-qa-automation/src/main/java/Help_positive_scenarios/Help_positive_scenarios.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner_Files.Help_positive_scenarios_runner -->
